### ISSUE TITLE
Expose assertHistoryEvent utility method from TestWorkflowRule

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1189]
SDKTestWorkflowRule has a very useful [assertHistoryEvent](https://github.com/temporalio/sdk-java/blob/master/temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java#L277) method
which would be nice to have exposed from public TestWorkflowRule as well.

It's possible for users to write this on their own currently, see forum post [here](https://community.temporal.io/t/method-temporal-api-workflowservice-v1-workflowservice-listworkflowexecutions-is-unimplemented-when-using-sdktestworkflowrule/4639). 
It would be nice to have it out of the box if possible.

**Comment by Spikhalskiy** [comment]
Users' code doesn't work with history events directly, it works with Temporal API. 
It's a bad practice for application test code to assert Temporal history events which is basically a Temporal internal abstraction.
Tests asserting that Temporal produces a correct internal state should be in Temporal tests, not in user tests
I think we will not expose the convenient methods for it because it will promote a wrong practice.
