### ISSUE TITLE
Calling synchronous workflow stub should propagate workflow exceptions

### ISSUE THREAD

**Issue by Bennett-Lynch** [temporalio/sdk-java#1369]
Steps to repro:
1. Create a trivial workflow impl that only throws an exception
2. Create a standard unit test with `TestWorkflowExtension` and register the workflow type
3. Call the workflow stub synchronously
4. Workflow method will forever-block, although the exception is logged in the Temporal workers

So far I've only encountered this in unit tests. Unsure if the same behavior applies to a real Temporal server.

Version: 1.14.0

**Comment by Spikhalskiy** [comment]
Create ApplicationFailure to fail a workflow. Any other exception other than subclasses of TemporalFailure lead to failure of workflow task, not a workflow.
This is a design choice that was made to allow users to fix unexpected exceptions and redeploy after that  instead of failing the workflow.
If you check the history of the workflow in question, you will find that workflow is not failed.

Close as it works as designed.

**Comment by Bennett-Lynch** [comment]
I see. Thank you @Spikhalskiy. Apologizes for not better reading the docs.

**Comment by Spikhalskiy** [comment]
@Bennett-Lynch No worries. We are planning to release a separate doc page covering failures and exceptions. We are not doing a great job explaining intricacies like that right now.
