### ISSUE TITLE
High level API to list workflows

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-java#1552]
For the SDK side safe rollout feature we need a user-friendly API for listing workflows.

We've recently added this to TS and Python, Go already exposed a somewhat friendly API.
Java needs this too.

This API belongs on `WorkflowClient` and should return some form of iterator that can be mapped into histories for the mass replayer. The history mapper ideally would support a `concurrency` option to speed up history fetching.

**Comment by cretz** [comment]
My implementation suggestion:

* Add `io.temporal.client.WorkflowExecution` class that is a high-level wrapper over `temporal.api.workflow.v1.WorkflowExecutionInfo`
  * Make sure it has raw proto access
* Add `io.temporal.client.WorkflowExecutionDescription` class that extends `WorkflowExecution` and is a high-level wrapper over `temporal.api.workflowservice.v1.DescribeWorkflowExecutionResponse` 
  * Make sure it has raw proto access (it has a singular workflow execution info inside it which is why it can extend the other one)
* Add `io.temporal.common.WorkflowExecutionHistory` that combines a raw `io.temporal.api.history.v1.History` and a `workflowId`
  * There is already `io.temporal.internal.common.WorkflowExecutionHistory` that is used by the replayer, I suggest this replace that
  * I think it'd make sense to put this in `io.temporal.client` too, but I could understand
  * Add a static `fromJson(String workflowId, String jsonString)` that builds this from our UI/tctl JSON format (there's already a helper)
  * Ideally we could have a `toJson` that doesn't store the workflow ID but does a normal proto-JSON on the history, but we either have to have that use our messed-up Go form of enum storage or have `fromJson` _also_ support the non-messed-up proto form which @dmitry has resisted
* Add `WorkflowClient.describe(String workflowId)` (and overload `describe(String workflowId, Optional<String> runId)`) that returns `WorkflowExecutionDescription`
* Add `WorkflowClient.list(String query)` that returns `Stream<WorkflowExecution>`. I don't expect people to care about options to this function at this time (can add overloads later). I do not expect users need to care about pagination, but if they did, we could easily add `WorkflowClient.listPaginated` that returned `Stream<WorkflowExecutionPage>` or something.
* Add `WorkflowClient.fetchHistoryEvents(String workflowId)`, `WorkflowClient.fetchHistoryEvents(String workflowId, Optional<String> runId)`, and `WorkflowClient.fetchHistoryEvents(WorkflowExecution execution)`
  * This should return `Stream<io.temporal.api.history.v1.HistoryEvent>`
  * I don't think people need to be able to filter to close-event only or to be able to "wait" just yet, but if we do think that will come and we don't want to explode the overloads, maybe we want to go ahead and require an options object
* Add `WorkflowClient.fetchHistory(String workflowId)`, `WorkflowClient.fetchHistory(String workflowId, Optional<String> runId)`, and `WorkflowClient.fetchHistory(WorkflowExecution execution)`
  * This should return `WorkflowExecutionHistory`
  * This should leverage `fetchHistoryEvents` underneath
  * I don't think people need to be able to filter to close-event only (yet)
  * This obviates the need for some kind of special map from execution list to history list. Instead, they can just take their `Stream<WorkflowExecution>` and `.map(myClient::fetchHistory)` and boom, they have `Stream<WorkflowExecutionHistory>`
    * And stream already has options for doing this in parallel if they want it faster somehow
* Add `Worker.replayWorkflowExecution(io.temporal.common.WorkflowExecutionHistory)`
  * This already exists, but would be up to discussion on whether the remove the non-workflow-ID having form or just overload it
  * You do not need a special call for `Worker.replayWorkflowExecutions(Stream<io.temporal.common.WorkflowExecutionHistory>)` because the caller can easily do that (and in parallel if they want) with the existing one

All of this now makes for a really cohesive listing, history fetching, and replaying API. Take this awesome example:

```java
public void runBeforeDeployment(WorkflowClient client, Worker worker, String workflowType) {
  client
    .list("WorkflowType = '" + workflowType + "'")
    .map(client::fetchHistory)
    .parallel()
    .map(worker::replayWorkflowExecution);
}
```

That is a pretty looking API. Of course they could have their own lambda that wraps the replay part if they want to capture errors and continue.

> The history mapper ideally would support a concurrency option to speed up history fetching.

Java already has utilities for parallel handling of streams and since we prefer to give users control over their threads on the client side, we should not add this ourselves.
