### ISSUE TITLE
Test with mock activity doesn't work with Mockito version 2

### ISSUE THREAD

**Issue by frank-le** [temporalio/sdk-java#332]
## Actual Behavior
Error: `This annotation can be used only on the interface method it implements.`

## Steps to Reproduce the Problem
Change Temporal-samples with the followings and just execute any test, e.g., HelloActivityTest
```
    testImplementation group: 'org.mockito', name: 'mockito-core', version: '2.28.2'
    testImplementation group: 'org.powermock', name: 'powermock-api-mockito2', version: '2.0.5'
```

## Specifications

  - Version: 10.3
  - Platform: MacOS

**Comment by GreyTeardrop** [comment]
I've faced the same issue with Mockito 2.x/3.x. As of version 2.0.0, Mockito has switched to annotating mock with all the annotations it can find on the source class or interface, which, in turn, makes Temporal's `POJOActivityImplMetadata` unhappy.

The workaround I've found is to create all activity mocks with a flag to disable annotation copying

```java
Mockito.mock(ActivityInterface.class, Mockito.withSettings().withoutAnnotations())
```

I wonder what would be the proper solution. Perhaps instead of making Temporal's SDK more lenient, upgrading examples repo to recent Mockito to display how `withoutAnnotations()` has to be used for all mocks would be enough?

**Comment by robzienert** [comment]
This is also a problem with [mockk](https://mockk.io/), but I haven't taken the time to investigate yet.

**Comment by GreyTeardrop** [comment]
I've opened up a [PR](https://github.com/temporalio/samples-java/pull/73) to the `samples-java` repository showing how Mockito 3 could be used to mock activities.

**Comment by Spikhalskiy** [comment]
Closing until more information is provided. Mockito 2 and 3 are used both in our own samples/ tests and by our users to mock activities from what I know. Feel free to reopen with a reproduction.
